---
# Copyright Alban Andrieu 2013-2017
# Distributed under the GPL-3.0
# (See accompanying file LICENSE.md)

sudo: required
dist: travis_lts

language: python
node_js:
  - "8"
  - "11"

python:
  #  - 2.7
  #  - 3.3
  #  - 3.4
  #  - 3.5
  - 3.6

services:
  - docker

branches:
  only:
    - master

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/47b10b81867bd0063cf5
      - https://galaxy.ansible.com/api/v1/notifications/
    on_success: change
    on_failure: always
    on_start: false

cache:
  pip: true
  npm: true
  yarn: true
  directories:
    - $HOME/.sonar/cache
    - $HOME/.cache
    - $HOME/.m2
    - node_modules

env:
  matrix:
    - PRIVATE_BOWER_VERSION=1.0.7
    - PRIVATE_BOWER_VERSION=1.1.9
  global:
    - JENKINS_HOME: /home/jenkins
    - JENKINS_UID: 3000
    - DOCKER_GID: 999
    - ANSIBLE_VERSION=2.8.1
    - secure: dFb9uIYQbUOIQIReGk49jcI1t6dNhyGXWpC6+xWYPSXMBpsE+GEHD4SjhUUfEfmb9oqvldW27D6h+gGqnGFnB6MKC/Ecijj9v2KsEFfDplm62piSh2gSd+02ZSIJQSTb2AsuesG7rIwjgtqtV/gN5+1FuJtQKgqIsW4MiAwNwPg=

matrix:
  fast_finish: true
  allow_failures:
    - env: PRIVATE_BOWER_VERSION=1.0.7

before_install:
  - npm config set spin false
  - npm install -g private-bower

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

  # Add ansible.cfg to pick up roles path.
  # - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Prepare tests
  # Add user jenkins to the image (travis is 2000)
  - id -a
  - getent passwd 3000 || true   #     3000 not found we can use it for jenkins user
  #  - groupadd -g ${DOCKER_GID} docker && \
  - sudo adduser --quiet --disabled-password --shell /bin/bash --uid ${JENKINS_UID} --gid ${DOCKER_GID} --home ${JENKINS_HOME} --gecos "Jenkins" jenkins
  # Set password for the jenkins user (you may want to alter this).
  #  - sudo echo "jenkins:jenkins1234" | sudo chpasswd

  - pip install molecule

  # Update Ansible submodule.
  - git pull && git submodule init && git submodule update && git submodule status
  - git submodule foreach git checkout master

  - ansible-galaxy install -r ./requirements.yml -p ./roles/ --ignore-errors

script:
  # Check ansible version
  - ansible --version

  # Check syntax
  - ansible-playbook --syntax-check ./private-bower.yml -vvvv --connection=local -e "private_bower_version=$PRIVATE_BOWER_VERSION"

  # Molecule test
  - molecule test

  # First run
  - sudo ansible-playbook --connection=local -vvvv ./private-bower.yml -e "private_bower_version=$PRIVATE_BOWER_VERSION"

  # Test role idempotence.
  - idempotence=$(mktemp)
  - ansible-playbook --connection=local -vvvv ./private-bower.yml -e "private_bower_version=$PRIVATE_BOWER_VERSION" | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Ensure private-bower is installed and at the right version.
  - 'which private-bower'
  - 'ls -lrta /usr/local/bin/private-bower'
  - 'private-bower --version'
