---
# Copyright Alban Andrieu 2013-2017
# Distributed under the GPL-3.0
# (See accompanying file LICENSE.md)

sudo: required
dist: travis_lts

script:
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- gcc --version

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

language: node_js
node_js:
  - "8"
  - "11"

branches:
  only:
  - master

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/47b10b81867bd0063cf5
    - https://galaxy.ansible.com/api/v1/notifications/
    on_success: change
    on_failure: always
    on_start: false

cache:
  pip: true
  npm: true
  yarn: true
  directories:
    - $HOME/.sonar/cache
    - $HOME/.cache
    - $HOME/.m2
    - node_modules

env:
  matrix:
  - PRIVATE_BOWER_VERSION: 1.0.7
  - PRIVATE_BOWER_VERSION: 1.1.9
#  - distro: ubuntu1604
#    distribution: ubuntu
#    version: 16.04
#    init: /sbin/init
#    run_opts: "--privileged"
#    playbook: test.yml
#    PRIVATE_BOWER_VERSION: 1.1.9
#  - distro: debian8
#    distribution: debian
#    version: 8
#    init: /lib/systemd/systemd
#    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
#    playbook: test.yml
#    PRIVATE_BOWER_VERSION: 1.1.9    
  global:
    secure: dFb9uIYQbUOIQIReGk49jcI1t6dNhyGXWpC6+xWYPSXMBpsE+GEHD4SjhUUfEfmb9oqvldW27D6h+gGqnGFnB6MKC/Ecijj9v2KsEFfDplm62piSh2gSd+02ZSIJQSTb2AsuesG7rIwjgtqtV/gN5+1FuJtQKgqIsW4MiAwNwPg=

matrix:
  fast_finish: true
  allow_failures:
  - env: PRIVATE_BOWER_VERSION=1.0.7

before_install:
  - npm config set spin false
#  - npm install -g private-bower

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

  # Add ansible.cfg to pick up roles path.
  #- "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Prepare tests
  # Add user jenkins to the image (travis is 2000)
  - id -a
  - getent passwd 3000 || true # 3000 not found we can use it for jenkins user
#  - groupadd -g ${DOCKER_GID} docker && \
  - sudo adduser --quiet --disabled-password --shell /bin/bash --uid ${JENKINS_UID} --gid ${DOCKER_GID} --home ${JENKINS_HOME} --gecos "Jenkins" jenkins
  # Set password for the jenkins user (you may want to alter this).
#  - sudo echo "jenkins:jenkins1234" | sudo chpasswd

  - pip install molecule

  # Update Ansible submodule.
  - git pull && git submodule init && git submodule update && git submodule status
  - git submodule foreach git checkout master

  - ansible-galaxy install -r requirements.yml -p ./roles/ --ignore-errors


script:
  # Check ansible version
  - ansible --version

  # Check syntax
  - ansible-playbook -i ./hosts --syntax-check private-bower.yml -vvvv --connection=local -e "python_versions=[2.7, 3.5]"

  # Molecule test
  # - molecule test

  # First run
  - ansible-playbook -i ./hosts --connection=local -vvvv private-bower.yml -e "python_versions=[2.7, 3.5]"
