---
# Copyright Alban Andrieu 2013-2017
# Distributed under the GPL-3.0
# (See accompanying file LICENSE.md)

sudo: required
dist: trusty

script:
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- gcc --version

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

language: node_js
node_js:
  - "8"
  - "11"

branches:
  only:
  - master

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/47b10b81867bd0063cf5
    - https://galaxy.ansible.com/api/v1/notifications/
    on_success: change
    on_failure: always
    on_start: false

cache:
  pip: true
  npm: true
  yarn: true
  directories:
    - $HOME/.sonar/cache
    - $HOME/.cache
    - $HOME/.m2
    - node_modules

env:
  matrix:
  - distro: ubuntu1404
    distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: "--privileged"
    playbook: test.yml
    PRIVATE_BOWER_VERSION: 1.1.9
  global:
    secure: dFb9uIYQbUOIQIReGk49jcI1t6dNhyGXWpC6+xWYPSXMBpsE+GEHD4SjhUUfEfmb9oqvldW27D6h+gGqnGFnB6MKC/Ecijj9v2KsEFfDplm62piSh2gSd+02ZSIJQSTb2AsuesG7rIwjgtqtV/gN5+1FuJtQKgqIsW4MiAwNwPg=

matrix:
  fast_finish: true
  allow_failures:
  - env: distro=ubuntu1604
  - env: distro=ubuntu1804

before_install:
  - npm config set spin false
#  - npm install -g private-bower

install:
  - npm install
