---
# Copyright Alban Andrieu 2013-2017
# Distributed under the GPL-3.0
# (See accompanying file LICENSE.md)

sudo: required
dist: trusty

script:
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
- gcc --version

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
#    - ruby-compass

language: node_js
node_js:
  - "8"
  - "11"

branches:
  only:
  - master

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/47b10b81867bd0063cf5
    on_success: change
    on_failure: always
    on_start: false

cache:
  pip: true
  npm: true
  yarn: true
  directories:
    - $HOME/.sonar/cache
    - $HOME/.cache
    - $HOME/.m2
    - node_modules

env:
  matrix:
  - EMBER_VERSION=default
  global:
    secure: dFb9uIYQbUOIQIReGk49jcI1t6dNhyGXWpC6+xWYPSXMBpsE+GEHD4SjhUUfEfmb9oqvldW27D6h+gGqnGFnB6MKC/Ecijj9v2KsEFfDplm62piSh2gSd+02ZSIJQSTb2AsuesG7rIwjgtqtV/gN5+1FuJtQKgqIsW4MiAwNwPg=

matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_VERSION=release
  - env: EMBER_VERSION=beta
  - env: EMBER_VERSION=canary

before_install:
  #- 'gem install sass --version "=3.2.12"'
  #- 'gem install compass --version "=0.12.2"'
  - 'gem install sass'
  - 'gem install compass'
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g bower karma grunt-cli jshint

install:
  - npm install
