---
# This playbook contains common plays that will be run on all nodes.

- name: private-bower | Install screen
  apt:
    pkg=screen
    state="present"
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  tags: private_bower_setup

- name: private-bower | Packages
  npm: >
    name={{ item }}
    state=present
    global=yes
    version={{ private_bower_version }}
  with_items:
    - private-bower
  sudo: yes
#  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')  
  tags: private_bower_setup

- name: private-bower | Copy the private-bower init script
  template:
    src: "private-bower-{{ ansible_distribution }}.sh.j2"
    dest: "/etc/init.d/private-bower"
    owner: root
    group: root
    mode: 0755
  sudo: yes  
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  tags: configure
  
- name: private-bower | Copy the private-bower backup script
  template:
    src: "rivate-bower-backup-{{ ansible_distribution }}.sh.j2"
    dest: "{{ private_bower_base_dir }}/bin/backup.sh"
    owner: root
    group: root
    mode: 0755  
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu') and private_bower_backup_enabled
  tags: configure  
  
- name: private-bower | Start the private-bower service
  service: name=private-bower state=started enabled=true
  tags: service  
        
#- debug: msg=" private-bower | Run private-bower"
- debug: msg=" private-bower | Avaialable at http://localhost:5678/"
