---
# This playbook contains common plays that will be run on all nodes.

- name: private-bower | Install screen (Debian based)
  apt:
    name={{ item }}
    state={{ private_bower_pkg_state }}
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  with_items:
   - screen
  tags: private_bower_setup
  become: yes

- name: private-bower | Install screen (RedHat based)
  yum:
   name={{ item }}
   state={{ private_bower_pkg_state }} update_cache=yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  with_items:
   - screen
  tags: private_bower_setup
  become: yes

- name: private-bower | Packages
  npm: >
    name={{ item }}
    state=present
    global=yes
    version={{ private_bower_version }}
  with_items:
    - private-bower
  become: yes
  tags: private_bower_setup

- name: private-bower | Copy the private-bower init script
  template:
    src: "private-bower.sh.j2"
    dest: "/etc/init.d/private-bower"
    owner: root
    group: root
    mode: 0755
  become: yes
  tags: configure

- name: private-bower | Copy the private-bower backup script
  template:
    src: "rivate-bower-backup.sh.j2"
    dest: "{{ private_bower_base_dir }}/bin/backup.sh"
    owner: root
    group: root
    mode: 0755
  when: private_bower_backup_enabled
  tags: configure

- name: private-bower | Copy the private-bower config file
  template:
    src: "{{ private_bower_conf }}.j2"
    dest: "{{ private_bower_base_dir }}/{{ private_bower_conf }}"
    owner: root
    group: root
    mode: 0755
  when: private_bower_backup_enabled
  tags: configure

#TODO add to user
#export GIT_SSL_NO_VERIFY=true
#export GIT_CURL_VERBOSE=1

- name: private-bower | Update git configuration (http.sslVerify)
  action: command git config --global http.sslVerify {{ shell_git_ssl }}
  become: yes

- name: private-bower | Start the private-bower service
  service: name=private-bower state=started enabled=true
  tags: service

#- debug: msg=" private-bower | Run private-bower"
- debug: msg=" private-bower | Avaialable at http://localhost:5678/"
